language: groovy
jdk:
- openjdk8
before_install:
- cat /etc/hosts
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo
  tee /etc/hosts
- cat /etc/hosts
before_script:
- rm -rf build
script: "./travis-build.sh"
env:
  global:
  - GIT_NAME="Puneet Behl"
  - GIT_EMAIL="behl4485@gmail.com"
  - secure: A8sAb+1/yBtLwHCedra3EmeLngsTZDy1hL+TZf+rS5rvwby6txfW0ji6nQ8Qc8NDuz3vpJdVfoFZi83daBh2MdV0iEYZ0QBCP0Yk23qWFKXf7jP3sTP0eTMgBUYEOoOgi4Rf/oe1jnrM1EcZy+IWSS+m9R6uzU43QmsScFiiQAM=
  - secure: sa796SjkySP4Nw7H5AYTzX1ERC3Qi0V4aTU9sFzaI4BdsN1HxjBocjnfR6ClQnoRasC5nmnDVzcjZmgZFm1/DWU0A53tjXUg/mLn6pXeKh3x+w1wV3x/ZJk/ImQV2C909mN6anBJRSM/JldfaXbgZyXG4mhAUFUM3LnLgkqUitU=
  - secure: QYDjOl8O0rQh/hRLU+pgSHqVs40rnNlDdjmxKvQxiqVZ9nXvGVkvldEpK1pcVA4+V9rl3C1dIp5MbdtbV6kLdmn83jp0jJ0hD/g217ujWMbPdpTq0yTBlXVGVPaoX2wUQ7ZZt/5T2NcMllvKXBFJOPYGuHETa5JrZ8yMMvIWujs=
  - secure: FmsgoVzerZWu7FpI3MgBttDTiklGfpo3HckD2VvbyK0YTedTbk+gi6JnG70IA0FVPiKAktcRQEejO9lVkZZPG26EYAC1gZmdvpVflRobcpThuYxKW1w+HzC9clS7+d4Nut2QZ/mkWJgFWPt1L7rQiJUp46QaXo/ipzfxhnQPdvI=
  - secure: pMTXBrqpocE8r8SxeM/2mc6RlrPlJqyuWb5Ady6RK/DLj8gSdePPR0j5GPFxRXh0fRCw37gSZDpi7MXiDTDIrcmcgbPMx+J3QYZcRoocMX1udyQJG61Er4OjAo4Cfbf0a+bVwvIOdTGnM1aGsXLIWqYi2LbC5Or1zxRRGRYqSBU=
  - secure: AmRMF3qlMsavALDihJ994rKsf3eiyy5rc/ILj8VKIACy0P5Uba6N33nCFTJSKNZusR3thdVU0gtEtQzaOFXEm2exD902VBMSGg93ctvB8qZo6qiGVIvzf/KfHFngp6iK79YgTe6p2LaZeEEWTAxScraUFTZKQA82UNaIFdweDsM=
  - secure: Hm9gbXchKYmpMAF3uAF9PHG0AF1FF6NHA55Gz3MzLiKyUpSpsyENXvR6NXN3ux1ckXUFFrkDKaPOg3mOJ/Xyhx0OxLvXX3l+wZEU9JRzwE/uoKV/SqqpYiVRLavlBlJeD+Xk9o/jbiU0iPWF0rZrZ30GmCHiGq2V/d69fgAS13I=
